/**
 * AUTOGENERATED BY scripts/generate_types.ts
 * DO NOT EDIT DIRECTLY. Source IDLs located in src/idl/ and AlchmAgentsSolana/target/idl/
 */

export type HackathonTrack = 'from-scratch' | 'extend-open-source' | 'ship-a-feature';

export interface HackStationMissionConfig {
  protocol: 'AlchmAgentsSolana';
  ecosystem: 'Pentacles';
  database: 'SpaceTimeDB';
  network: 'devnet' | 'testnet' | 'mainnet-beta' | 'localnet';
  tokenProgram: 'Token-2022' | 'SPL-Token';
}

/* =========================================================================
   KNOWN PROGRAM IDENTIFIERS & PDA SEEDS
   ========================================================================= */
export const PROGRAM_IDS = {
  ASOL_PROGRAM: '5QheuqaicKvPPRFEoEXwaE5xaFp7gauvJCfsjpQv8WzD',
  TOKEN2022_TRANSFER_HOOK: 'Hook1gNisFeeResoLver1111111111111111111111111',
  ALCHM_STAKING_VAULTS: 'Vault11111111111111111111111111111111111111',
} as const;

export const PDA_SEEDS = {
  EXTRA_ACCOUNT_METAS: 'extra-account-metas',
  STAR_VAULT: 'star-vault',
  STAR_POOL: 'star-pool',
  RECONCILIATION_RECORD: 'reconcile-spacetime',
} as const;

/* =========================================================================
   PROGRAM: asol_program (from asol_program.json)
   ========================================================================= */
export const ASOLPROGRAM_ADDRESS = '5QheuqaicKvPPRFEoEXwaE5xaFp7gauvJCfsjpQv8WzD';

// Instructions for AsolProgram
export interface ActivateStarArgs {
  star_id: number;
  proof: Array<Array<number> /* len: 32 */>;
}

export interface ActivateStarAccounts {
  star_vault_state: string; // readonly, non-signer
  star_pool: string; // mut, non-signer
  payer: string; // mut, signer
  system_program: string; // readonly, non-signer
}

export interface AddLiquidityArgs {
  pool_id: number;
  amt_a: bigint | number | string;
  amt_b: bigint | number | string;
  min_shares: bigint | number | string;
  region_commit: Array<number> /* len: 32 */;
  visible_stars: number;
  nonce: bigint | number | string;
  deadline: bigint | number | string;
}

export interface AddLiquidityAccounts {
  program_config: string; // readonly, non-signer
  pool: string; // mut, non-signer
  trader: string; // mut, signer
  nonce_account: string; // mut, non-signer
  mint_a: string; // mut, non-signer
  mint_b: string; // mut, non-signer
  trader_mint_a_ata: string; // mut, non-signer
  trader_mint_b_ata: string; // mut, non-signer
  deed_position: string; // mut, non-signer
  instructions: string; // readonly, non-signer
  token_2022_program: string; // readonly, non-signer
  system_program: string; // readonly, non-signer
}

export interface BootstrapPoolArgs {
  pool_id: number;
  reserve_a: bigint | number | string;
  reserve_b: bigint | number | string;
}

export interface BootstrapPoolAccounts {
  program_config: string; // readonly, non-signer
  admin: string; // mut, signer
  pool: string; // mut, non-signer
}

export interface ClaimMintEsmsArgs {
  claim_id: Array<number> /* len: 32 */;
  ledger_reference_hash: Array<number> /* len: 32 */;
  amounts: Array<bigint | number | string> /* len: 4 */;
}

export interface ClaimMintEsmsAccounts {
  program_config: string; // readonly, non-signer
  claim_receipt: string; // mut, non-signer
  authority: string; // mut, signer
  recipient: string; // readonly, non-signer
  spirit_mint: string; // mut, non-signer
  essence_mint: string; // mut, non-signer
  matter_mint: string; // mut, non-signer
  substance_mint: string; // mut, non-signer
  spirit_account: string; // mut, non-signer
  essence_account: string; // mut, non-signer
  matter_account: string; // mut, non-signer
  substance_account: string; // mut, non-signer
  token_program: string; // readonly, non-signer
  associated_token_program: string; // readonly, non-signer
  system_program: string; // readonly, non-signer
}

export interface ClaimStarYieldArgs {
  star_id: number;
  element_id: number;
  amount: bigint | number | string;
  nonce: bigint | number | string;
  deadline: bigint | number | string;
}

export interface ClaimStarYieldAccounts {
  program_config: string; // readonly, non-signer
  star_vault_state: string; // readonly, non-signer
  stake_position: string; // mut, non-signer
  staker: string; // mut, signer
  element_mint: string; // mut, non-signer
  staker_element_ata: string; // mut, non-signer
  instructions: string; // readonly, non-signer
  token_2022_program: string; // readonly, non-signer
  associated_token_program: string; // readonly, non-signer
  system_program: string; // readonly, non-signer
}

export interface InitializeConfigArgs {
  attestor: string;
  pauser: string;
  cluster_domain: Array<number> /* len: 32 */;
}

export interface InitializeConfigAccounts {
  program_config: string; // mut, non-signer
  admin: string; // mut, signer
  program: string; // readonly, non-signer
  program_data: string; // readonly, non-signer
  system_program: string; // readonly, non-signer
}

export type InitializeEsmsMintsArgs = Record<string, never>;

export interface InitializeEsmsMintsAccounts {
  program_config: string; // readonly, non-signer
  admin: string; // mut, signer
  spirit_mint: string; // mut, non-signer
  essence_mint: string; // mut, non-signer
  matter_mint: string; // mut, non-signer
  substance_mint: string; // mut, non-signer
  token_program: string; // readonly, non-signer
  system_program: string; // readonly, non-signer
}

export interface InitializeStarVaultArgs {
  star_root: Array<number> /* len: 32 */;
  max_yield_rate_per_usdc_day: bigint | number | string;
}

export interface InitializeStarVaultAccounts {
  star_vault_state: string; // mut, non-signer
  admin: string; // mut, signer
  program_config: string; // readonly, non-signer
  usdc_mint: string; // readonly, non-signer
  vault_usdc_ata: string; // readonly, non-signer
  system_program: string; // readonly, non-signer
}

export interface RecordPersonaCommitmentArgs {
  agent_id: Array<number> /* len: 32 */;
  target_persona_hash: Array<number> /* len: 32 */;
  epoch_hash: Array<number> /* len: 32 */;
  sequence: bigint | number | string;
}

export interface RecordPersonaCommitmentAccounts {
  program_config: string; // readonly, non-signer
  persona_commitment: string; // mut, non-signer
  writer: string; // mut, signer
  system_program: string; // readonly, non-signer
}

export interface RedeemEsmsArgs {
  order_id: Array<number> /* len: 32 */;
  amounts: Array<bigint | number | string> /* len: 4 */;
}

export interface RedeemEsmsAccounts {
  program_config: string; // readonly, non-signer
  order_receipt: string; // mut, non-signer
  holder: string; // mut, signer
  spirit_mint: string; // mut, non-signer
  essence_mint: string; // mut, non-signer
  matter_mint: string; // mut, non-signer
  substance_mint: string; // mut, non-signer
  spirit_account: string; // mut, non-signer
  essence_account: string; // mut, non-signer
  matter_account: string; // mut, non-signer
  substance_account: string; // mut, non-signer
  token_program: string; // readonly, non-signer
  system_program: string; // readonly, non-signer
}

export interface RedeemForEsmsArgs {
  order_id: Array<number> /* len: 32 */;
  amounts: Array<bigint | number | string> /* len: 4 */;
  deadline: bigint | number | string;
}

export interface RedeemForEsmsAccounts {
  program_config: string; // readonly, non-signer
  order_receipt: string; // mut, non-signer
  sponsor: string; // mut, signer
  holder: string; // readonly, non-signer
  spirit_mint: string; // mut, non-signer
  essence_mint: string; // mut, non-signer
  matter_mint: string; // mut, non-signer
  substance_mint: string; // mut, non-signer
  spirit_account: string; // mut, non-signer
  essence_account: string; // mut, non-signer
  matter_account: string; // mut, non-signer
  substance_account: string; // mut, non-signer
  instructions: string; // readonly, non-signer
  token_program: string; // readonly, non-signer
  system_program: string; // readonly, non-signer
}

export interface RegisterPoolArgs {
  pool_id: number;
  element_a: number;
  element_b: number;
  fee_bps: number;
}

export interface RegisterPoolAccounts {
  program_config: string; // readonly, non-signer
  admin: string; // mut, signer
  pool: string; // mut, non-signer
  system_program: string; // readonly, non-signer
}

export interface SetPauseStateArgs {
  pause_claims: boolean;
  pause_redemptions: boolean;
}

export interface SetPauseStateAccounts {
  program_config: string; // mut, non-signer
  authority: string; // readonly, signer
}

export interface SetPoolPauseArgs {
  pool_id: number;
  paused: boolean;
}

export interface SetPoolPauseAccounts {
  program_config: string; // readonly, non-signer
  authority: string; // readonly, signer
  pool: string; // mut, non-signer
}

export interface SetServiceAuthoritiesArgs {
  attestor: string;
  pauser: string;
}

export interface SetServiceAuthoritiesAccounts {
  program_config: string; // mut, non-signer
  authority: string; // readonly, signer
}

export interface SetStarVaultConfigArgs {
  star_root: Array<number> /* len: 32 */ | null;
  max_yield_rate_per_usdc_day: bigint | number | string | null;
}

export interface SetStarVaultConfigAccounts {
  star_vault_state: string; // mut, non-signer
  admin: string; // readonly, signer
}

export interface StakeStarArgs {
  star_id: number;
  usdc_amount: bigint | number | string;
}

export interface StakeStarAccounts {
  star_vault_state: string; // mut, non-signer
  star_pool: string; // mut, non-signer
  stake_position: string; // mut, non-signer
  staker: string; // mut, signer
  usdc_mint: string; // readonly, non-signer
  staker_usdc_ata: string; // mut, non-signer
  vault_usdc_ata: string; // mut, non-signer
  token_program: string; // readonly, non-signer
  system_program: string; // readonly, non-signer
}

export interface SwapEsmsArgs {
  pool_id: number;
  in_element: number;
  in_amount: bigint | number | string;
  min_out: bigint | number | string;
  region_commit: Array<number> /* len: 32 */;
  visible_stars: number;
  nonce: bigint | number | string;
  deadline: bigint | number | string;
}

export interface SwapEsmsAccounts {
  program_config: string; // readonly, non-signer
  pool: string; // mut, non-signer
  trader: string; // mut, signer
  nonce_account: string; // mut, non-signer
  mint_a: string; // mut, non-signer
  mint_b: string; // mut, non-signer
  trader_in_ata: string; // mut, non-signer
  trader_out_ata: string; // mut, non-signer
  instructions: string; // readonly, non-signer
  token_2022_program: string; // readonly, non-signer
  associated_token_program: string; // readonly, non-signer
  system_program: string; // readonly, non-signer
}

export interface UnstakeStarArgs {
  star_id: number;
  shares: bigint | number | string;
}

export interface UnstakeStarAccounts {
  star_vault_state: string; // mut, non-signer
  star_pool: string; // mut, non-signer
  stake_position: string; // mut, non-signer
  staker: string; // mut, signer
  usdc_mint: string; // readonly, non-signer
  staker_usdc_ata: string; // mut, non-signer
  vault_usdc_ata: string; // mut, non-signer
  token_program: string; // readonly, non-signer
}

export interface WithdrawLiquidityArgs {
  pool_id: number;
  share_bps: number;
}

export interface WithdrawLiquidityAccounts {
  program_config: string; // readonly, non-signer
  pool: string; // mut, non-signer
  owner: string; // mut, signer
  mint_a: string; // mut, non-signer
  mint_b: string; // mut, non-signer
  owner_mint_a_ata: string; // mut, non-signer
  owner_mint_b_ata: string; // mut, non-signer
  deed_position: string; // mut, non-signer
  token_2022_program: string; // readonly, non-signer
  associated_token_program: string; // readonly, non-signer
  system_program: string; // readonly, non-signer
}

// Account States for AsolProgram
export interface ClaimReceiptState {
}

export interface ConstellationPoolState {
}

export interface DeedPositionState {
}

export interface OrderReceiptState {
}

export interface PersonaCommitmentState {
}

export interface PoolTraderNonceState {
}

export interface ProgramConfigState {
}

export interface StakePositionState {
}

export interface StarPoolState {
}

export interface StarVaultStateState {
}

// Custom Types for AsolProgram
export interface ClaimReceipt {
  version: number;
  claim_id: Array<number> /* len: 32 */;
  ledger_reference_hash: Array<number> /* len: 32 */;
  recipient: string;
  amounts: Array<bigint | number | string> /* len: 4 */;
  authority: string;
  settled_slot: bigint | number | string;
  bump: number;
}

export interface ConstellationPool {
  version: number;
  pool_id: number;
  element_a: number;
  element_b: number;
  fee_bps: number;
  reserve_a: bigint | number | string;
  reserve_b: bigint | number | string;
  total_shares: bigint | number | string;
  bootstrapped: boolean;
  paused: boolean;
  bump: number;
}

export interface DeedPosition {
  version: number;
  pool_id: number;
  owner: string;
  shares: bigint | number | string;
  created_slot: bigint | number | string;
  bump: number;
}

export interface LiquidityAdded {
  pool_id: number;
  trader: string;
  amt_a: bigint | number | string;
  amt_b: bigint | number | string;
  shares: bigint | number | string;
  deed_position: string;
  region_commit: Array<number> /* len: 32 */;
  visible_stars: number;
}

export interface LiquidityWithdrawn {
  pool_id: number;
  trader: string;
  deed_position: string;
  pull_shares: bigint | number | string;
  remaining_shares: bigint | number | string;
  amt_a: bigint | number | string;
  amt_b: bigint | number | string;
  reserve_a: bigint | number | string;
  reserve_b: bigint | number | string;
}

export interface OrderReceipt {
  version: number;
  order_id: Array<number> /* len: 32 */;
  holder: string;
  amounts: Array<bigint | number | string> /* len: 4 */;
  submitter: string;
  mode: number;
  settled_slot: bigint | number | string;
  bump: number;
}

export interface PersonaCommitment {
  version: number;
  agent_id: Array<number> /* len: 32 */;
  target_persona_hash: Array<number> /* len: 32 */;
  epoch_hash: Array<number> /* len: 32 */;
  sequence: bigint | number | string;
  writer: string;
  updated_slot: bigint | number | string;
  bump: number;
}

export interface PoolBootstrapped {
  pool_id: number;
  reserve_a: bigint | number | string;
  reserve_b: bigint | number | string;
  total_shares: bigint | number | string;
}

export interface PoolPauseToggled {
  pool_id: number;
  paused: boolean;
}

export interface PoolRegistered {
  pool_id: number;
  element_a: number;
  element_b: number;
  fee_bps: number;
}

export interface PoolTraderNonce {
  version: number;
  pool_id: number;
  trader: string;
  nonce: bigint | number | string;
  bump: number;
}

export interface ProgramConfig {
  version: number;
  admin: string;
  attestor: string;
  pauser: string;
  cluster_domain: Array<number> /* len: 32 */;
  pause_claims: boolean;
  pause_redemptions: boolean;
  bump: number;
}

export interface StakePosition {
  version: number;
  staker: string;
  star_id: number;
  shares: bigint | number | string;
  principal: bigint | number | string;
  accrued_cap: bigint | number | string;
  last_checkpoint: bigint | number | string;
  claim_nonce: bigint | number | string;
  bump: number;
}

export interface StarPool {
  version: number;
  star_id: number;
  activated: boolean;
  total_principal: bigint | number | string;
  total_shares: bigint | number | string;
  bump: number;
}

export interface StarVaultState {
  version: number;
  admin: string;
  usdc_mint: string;
  vault_usdc_ata: string;
  total_principal: bigint | number | string;
  star_root: Array<number> /* len: 32 */;
  max_yield_rate_per_usdc_day: bigint | number | string;
  bump: number;
}

export interface Swapped {
  pool_id: number;
  trader: string;
  in_element: number;
  in_amount: bigint | number | string;
  out_element: number;
  out_amount: bigint | number | string;
  reserve_a: bigint | number | string;
  reserve_b: bigint | number | string;
  region_commit: Array<number> /* len: 32 */;
  visible_stars: number;
}


/* =========================================================================
   PROGRAM: alchm_staking_vaults (from alchm_staking_vaults.json)
   ========================================================================= */
export const ALCHMSTAKINGVAULTS_ADDRESS = 'AlchmStakingVaults1111111111111111111111111';

// Instructions for AlchmStakingVaults
export interface InitializeVaultArgs {
  starHipId: string;
  element: string;
  baseApy: number;
}

export interface InitializeVaultAccounts {
  vault: string; // mut, non-signer
  authority: string; // mut, signer
  systemProgram: string; // readonly, non-signer
}

export interface DepositStakeArgs {
  amount: bigint | number | string;
}

export interface DepositStakeAccounts {
  vault: string; // mut, non-signer
  staker: string; // mut, signer
  stakerTokenAccount: string; // mut, non-signer
  vaultTokenAccount: string; // mut, non-signer
  tokenProgram: string; // readonly, non-signer
}

export interface ClaimElementalRewardsArgs {
  astrometryMultiplier: number;
}

export interface ClaimElementalRewardsAccounts {
  vault: string; // mut, non-signer
  staker: string; // mut, signer
  elementalMint: string; // mut, non-signer
  recipientTokenAccount: string; // mut, non-signer
  tokenProgram2022: string; // readonly, non-signer
}

export interface ReconcileSpacetimeArgs {
  spacetimeRowIndex: bigint | number | string;
  stateCommitmentHash: Array<number> /* len: 32 */;
}

export interface ReconcileSpacetimeAccounts {
  vault: string; // mut, non-signer
  governanceAuthority: string; // readonly, signer
  reconciliationRecord: string; // mut, non-signer
}

// Account States for AlchmStakingVaults
export interface VaultState {
  authority: string;
  starHipId: string;
  element: string;
  baseApy: number;
  totalStakedLamports: bigint | number | string;
  lastReconciledSlot: bigint | number | string;
}


/* =========================================================================
   PROGRAM: token2022_transfer_hook (from token2022_transfer_hook.json)
   ========================================================================= */
export const TOKEN2022TRANSFERHOOK_ADDRESS = 'Hook1gNisFeeResoLver1111111111111111111111111';

// Instructions for Token2022TransferHook
export type InitializeExtraAccountMetaListArgs = Record<string, never>;

export interface InitializeExtraAccountMetaListAccounts {
  extraAccountMetaList: string; // mut, non-signer
  mint: string; // readonly, non-signer
  authority: string; // mut, signer
  systemProgram: string; // readonly, non-signer
}

export interface TransferHookArgs {
  amount: bigint | number | string;
}

export interface TransferHookAccounts {
  source: string; // readonly, non-signer
  mint: string; // readonly, non-signer
  destination: string; // readonly, non-signer
  owner: string; // readonly, non-signer
  extraAccountMetaList: string; // readonly, non-signer
  feeVault: string; // mut, non-signer
}

