import fs from 'fs';
import path from 'path';

interface IdlField {
  name: string;
  type: any;
}

interface IdlAccount {
  name: string;
  type?: {
    kind: string;
    fields: IdlField[];
  };
}

interface IdlInstruction {
  name: string;
  accounts?: Array<{
    name: string;
    isMut?: boolean;
    isSigner?: boolean;
    writable?: boolean;
    signer?: boolean;
  }>;
  args?: IdlField[];
}

interface Idl {
  version?: string;
  name: string;
  address?: string;
  instructions?: IdlInstruction[];
  accounts?: IdlAccount[];
  types?: any[];
  events?: any[];
  metadata?: {
    address?: string;
    origin?: string;
  };
}

// Convert Rust/Anchor types to TypeScript
function rustTypeToTs(type: any): string {
  if (typeof type === 'string') {
    const arrayMatch = type.match(/^\[\s*([^;]+)\s*;\s*(\d+)\s*\]$/);
    if (arrayMatch) {
      const inner = rustTypeToTs(arrayMatch[1].trim());
      return `Array<${inner}> /* len: ${arrayMatch[2]} */`;
    }

    switch (type) {
      case 'bool': return 'boolean';
      case 'u8':
      case 'i8':
      case 'u16':
      case 'i16':
      case 'u32':
      case 'i32':
      case 'f32':
      case 'f64': return 'number';
      case 'u64':
      case 'i64':
      case 'u128':
      case 'i128': return 'bigint | number | string';
      case 'string': return 'string';
      case 'publicKey':
      case 'pubkey': return 'string';
      default: return type;
    }
  }

  if (typeof type === 'object') {
    if (type.option) return `${rustTypeToTs(type.option)} | null`;
    if (type.vec) return `Array<${rustTypeToTs(type.vec)}>`;
    if (type.array) {
      const [innerType, len] = type.array;
      return `Array<${rustTypeToTs(innerType)}> /* len: ${len} */`;
    }
    if (type.defined) return type.defined;
  }

  return 'any';
}

function toPascalCase(str: string): string {
  return str
    .replace(/[-_](\w)/g, (_, c) => c.toUpperCase())
    .replace(/^(\w)/, (_, c) => c.toUpperCase());
}

async function runSync() {
  const asolIdlDir = path.resolve(process.cwd(), '../AlchmAgentsSolana/target/idl');
  const hackStationIdlDir = path.resolve(process.cwd(), 'src/idl');
  const pentaclesIdlDir = path.resolve(process.cwd(), '../Spacetimedbhackathon/Pentacles/src/idl');
  const pentaclesTargetIdlDir = path.resolve(process.cwd(), '../Spacetimedbhackathon/Pentacles/target/idl');

  fs.mkdirSync(hackStationIdlDir, { recursive: true });
  fs.mkdirSync(pentaclesIdlDir, { recursive: true });
  fs.mkdirSync(pentaclesTargetIdlDir, { recursive: true });

  let synced = 0;

  if (fs.existsSync(asolIdlDir)) {
    const files = fs.readdirSync(asolIdlDir).filter((f) => f.endsWith('.json'));
    for (const f of files) {
      const content = fs.readFileSync(path.join(asolIdlDir, f), 'utf-8');
      fs.writeFileSync(path.join(hackStationIdlDir, f), content, 'utf-8');
      fs.writeFileSync(path.join(pentaclesIdlDir, f), content, 'utf-8');
      fs.writeFileSync(path.join(pentaclesTargetIdlDir, f), content, 'utf-8');
      synced++;
      console.log(`[SYNC] Synced ${f} from ASOL to HackStation & Pentacles`);
    }
  }

  const canonicalIdls = ['alchm_staking_vaults.json', 'token2022_transfer_hook.json'];
  for (const idl of canonicalIdls) {
    const localPath = path.join(hackStationIdlDir, idl);
    if (fs.existsSync(localPath)) {
      const content = fs.readFileSync(localPath, 'utf-8');
      fs.writeFileSync(path.join(pentaclesIdlDir, idl), content, 'utf-8');
      fs.writeFileSync(path.join(pentaclesTargetIdlDir, idl), content, 'utf-8');
      synced++;
    }
  }

  console.log(`[SYNC COMPLETE] Total synchronized IDL copies: ${synced}`);
}

async function main() {
  const args = process.argv.slice(2);
  if (args.includes('--sync')) {
    await runSync();
  }

  const idlDir = path.resolve(process.cwd(), 'src/idl');
  if (!fs.existsSync(idlDir)) {
    console.error(`IDL directory does not exist: ${idlDir}`);
    process.exit(1);
  }

  const files = fs.readdirSync(idlDir).filter((f) => f.endsWith('.json'));
  console.log(`[TYPEGEN] Found ${files.length} IDLs: ${files.join(', ')}`);

  let code = `/**
 * AUTOGENERATED BY scripts/generate_types.ts
 * DO NOT EDIT DIRECTLY. Source IDLs located in src/idl/ and AlchmAgentsSolana/target/idl/
 */

export type HackathonTrack = 'from-scratch' | 'extend-open-source' | 'ship-a-feature';

export interface HackStationMissionConfig {
  protocol: 'AlchmAgentsSolana';
  ecosystem: 'Pentacles';
  database: 'SpaceTimeDB';
  network: 'devnet' | 'testnet' | 'mainnet-beta' | 'localnet';
  tokenProgram: 'Token-2022' | 'SPL-Token';
}

/* =========================================================================
   KNOWN PROGRAM IDENTIFIERS & PDA SEEDS
   ========================================================================= */
export const PROGRAM_IDS = {
  ASOL_PROGRAM: '5QheuqaicKvPPRFEoEXwaE5xaFp7gauvJCfsjpQv8WzD',
  TOKEN2022_TRANSFER_HOOK: 'Hook1gNisFeeResoLver111111111111111111111111',
  ALCHM_STAKING_VAULTS: 'Vault11111111111111111111111111111111111111',
} as const;

export const PDA_SEEDS = {
  EXTRA_ACCOUNT_METAS: 'extra-account-metas',
  STAR_VAULT: 'star-vault',
  STAR_POOL: 'star-pool',
  RECONCILIATION_RECORD: 'reconcile-spacetime',
} as const;
`;

  for (const file of files) {
    const idlPath = path.join(idlDir, file);
    try {
      const raw = fs.readFileSync(idlPath, 'utf-8');
      const idl: Idl = JSON.parse(raw);
      const resolvedName = idl.name || idl.metadata?.name || path.basename(file, '.json');
      const programName = toPascalCase(resolvedName);

      code += `\n/* =========================================================================\n`;
      code += `   PROGRAM: ${resolvedName} (from ${file})\n`;
      code += `   ========================================================================= */\n`;

      if (idl.metadata?.address || idl.address) {
        code += `export const ${programName.toUpperCase()}_ADDRESS = '${idl.metadata?.address || idl.address}';\n\n`;
      }

      // 1. Instructions
      if (idl.instructions && idl.instructions.length > 0) {
        code += `// Instructions for ${programName}\n`;
        for (const ix of idl.instructions) {
          const ixName = toPascalCase(ix.name);

          // Args
          if (ix.args && ix.args.length > 0) {
            code += `export interface ${ixName}Args {\n`;
            for (const arg of ix.args) {
              code += `  ${arg.name}: ${rustTypeToTs(arg.type)};\n`;
            }
            code += `}\n\n`;
          } else {
            code += `export type ${ixName}Args = Record<string, never>;\n\n`;
          }

          // Accounts
          if (ix.accounts && ix.accounts.length > 0) {
            code += `export interface ${ixName}Accounts {\n`;
            for (const acc of ix.accounts) {
              const isMut = acc.isMut ?? acc.writable ?? false;
              const isSigner = acc.isSigner ?? acc.signer ?? false;
              code += `  ${acc.name}: string; // ${isMut ? 'mut' : 'readonly'}, ${isSigner ? 'signer' : 'non-signer'}\n`;
            }
            code += `}\n\n`;
          }
        }
      }

      // 2. Accounts
      if (idl.accounts && idl.accounts.length > 0) {
        code += `// Account States for ${programName}\n`;
        for (const acc of idl.accounts) {
          const accName = toPascalCase(acc.name);
          code += `export interface ${accName}State {\n`;
          if (acc.type?.fields) {
            for (const field of acc.type.fields) {
              code += `  ${field.name}: ${rustTypeToTs(field.type)};\n`;
            }
          }
          code += `}\n\n`;
        }
      }

      // 3. User-defined types
      if (idl.types && idl.types.length > 0) {
        code += `// Custom Types for ${programName}\n`;
        for (const t of idl.types) {
          const tName = toPascalCase(t.name);
          if (t.type?.kind === 'struct' && t.type?.fields) {
            code += `export interface ${tName} {\n`;
            for (const f of t.type.fields) {
              code += `  ${f.name}: ${rustTypeToTs(f.type)};\n`;
            }
            code += `}\n\n`;
          } else if (t.type?.kind === 'enum' && t.type?.variants) {
            const variants = t.type.variants.map((v: any) => `'${v.name}'`).join(' | ');
            code += `export type ${tName} = ${variants};\n\n`;
          }
        }
      }
    } catch (err) {
      console.warn(`[TYPEGEN] Skipping ${file} due to parse error:`, err);
    }
  }

  const targetFile = path.resolve(process.cwd(), 'src/types/hackstation.ts');
  fs.writeFileSync(targetFile, code, 'utf-8');
  console.log(`[TYPEGEN] Successfully wrote updated types to ${targetFile}`);
}

main().catch((err) => {
  console.error('[TYPEGEN FATAL]', err);
  process.exit(1);
});
